from PIL import Image

from ...config import maiconfig
from ...constants import RANK_MAP
from ...resources import pic_dir
from ..merge.models import (
    Category,
    NotPlayedResult,
    PlayedResult,
    RiseResult,
    ServiceName,
    Theme,
)
from .base import ScoreBaseImage, change_column_width, coloum_width
from .tools import image_to_base64, song_chart


class DrawScore(ScoreBaseImage):
    def __init__(self, service: ServiceName, image: Image.Image) -> None:
        self.service = service
        self.theme = Theme.PRISM_PLUS
        super().__init__(image, self.theme)
        self._pic_theme_path = pic_dir / self.theme.value
        self._im.alpha_composite(self._aurora_bg)
        self._im.alpha_composite(self._shines_bg, (11, 6))
        self._im.alpha_composite(self._rainbow_bg, (318, self._im.size[1] - 545))
        self._im.alpha_composite(self._rainbow_bottom_bg, (122, self._im.size[1] - 305))
        for h in range((self._im.size[1] // 358) + 1):
            self._im.alpha_composite(self._pattern_bg, (0, (358 + 7) * h))
        self._design_bg = self._themed_image(self.theme, "design.png")
        self._title_lengthen_bg = self._themed_image(self.theme, "title_lengthen.png")
        self._design_text = (
            f"Designed by Yuri-YuzuChaN & BlueDeer233. Data from {service.value}. "
            f"Generated by {maiconfig.bot_name} BOT"
        )

    def _while_pic(self, data: list[NotPlayedResult], start_y: int = 200):
        """
        循环绘制谱面

        Params:
            `data`: `谱面数据`
            `y`: `y轴坐标`
        """
        step = 65
        start_x = 55
        base_y = start_y
        for num, v in enumerate(data):
            row, col = divmod(num, 20)

            x = start_x + col * step
            y = base_y + row * step

            cover = Image.open(song_chart(v.song_id)).resize((55, 55))
            self._im.alpha_composite(cover, (x, y))
            self._im.alpha_composite(self._diff_pg_bg[v.level_index], (x - 4, y - 4))
            self._tb.draw(
                x + 36, y + 3, 12, v.song_id, self._diff_text_color[v.level_index], "mm"
            )

    def while_rise_pic(self, data: list[RiseResult], low_score: int, isdx: bool):
        """
        循环绘制上分推荐数据

        Params:
            `data`: `上分数据`
            `low_score`: `最低分`
            `isdx`: `是否DX版本`
        """
        start_y = 120
        height = 140
        base_x = 200 if isdx else 700
        for index, _d in enumerate(data):
            x = base_x
            y = start_y + index * height

            rate = Image.open(
                self._pic_theme_path / f"UI_TTR_Rank_{RANK_MAP[_d.rate]}.png"
            ).resize((63, 28))

            self._im.alpha_composite(self._rise_bg[_d.level_index], (x + 30, y))
            self._im.alpha_composite(
                Image.open(song_chart(_d.song_id)).resize((80, 80)), (x + 55, y + 41)
            )
            self._im.alpha_composite(
                Image.open(pic_dir / f"{_d.type.upper()}.png").resize((60, 22)),
                (x + 240, y + 114),
            )
            if _d.old_rate:
                oldrate = Image.open(
                    self._pic_theme_path / f"UI_TTR_Rank_{_d.old_rate}.png"
                ).resize((63, 28))
                self._im.alpha_composite(oldrate, (x + 145, y + 82))
            self._im.alpha_composite(rate, (x + 305, y + 82))

            diff_color = self._diff_text_color[_d.level_index]
            id_color = self._id_text_color[_d.level_index]

            title = _d.song_name
            if coloum_width(title) > 26:
                title = change_column_width(title, 25) + "..."
            self._sy.draw(x + 142, y + 44, 17, title, diff_color, "lm")
            self._tb.draw(x + 145, y + 124, 18, f"ID: {_d.song_id}", id_color, "lm")
            self._tb.draw(
                x + 210,
                y + 71,
                25,
                f"{_d.old_achievements:.4f}%",
                diff_color,
                anchor="mm",
            )
            self._tb.draw(
                x + 245, y + 96, 17, f"Ra: {_d.old_rating}", diff_color, anchor="mm"
            )
            self._tb.draw(
                x + 370, y + 71, 25, f"{_d.achievements:.4f}%", diff_color, anchor="mm"
            )
            self._tb.draw(
                x + 415, y + 96, 17, f"Ra: {_d.rating}", diff_color, anchor="mm"
            )
            self._tb.draw(
                x + 315, y + 124, 18, f"ds:{_d.level_value}", id_color, anchor="lm"
            )
            if _d.old_rating > low_score:
                new_ra = _d.rating - _d.old_rating
            else:
                new_ra = _d.rating - low_score
            self._tb.draw(x + 390, y + 124, 18, f"Ra +{new_ra}", id_color, "lm")

    def draw_rise(
        self,
        sd: list[RiseResult],
        sd_score: int,
        dx: list[RiseResult],
        dx_score: int,
        total_height: int,
    ) -> str:
        """
        绘制上分数据表

        Params:
            `sd`: `旧版本谱面`
            `sd_score`: `旧版本最低分`
            `sd`: `新版本谱面`
            `dx_score`: `新版本最低分`
        Returns:
            `base64 str`
        """
        title_bg = self._title_bg.copy().resize((273, 80))
        self._im.alpha_composite(title_bg, (314, 30))
        self._sy.draw(450, 68, 18, "旧版本谱面推荐", self._default_text_color, "mm")
        self.while_rise_pic(sd, sd_score, True)
        self._im.alpha_composite(title_bg, (814, 30))
        self._sy.draw(950, 68, 18, "新版本谱面推荐", self._default_text_color, "mm")
        self.while_rise_pic(dx, dx_score, False)

        height = self._im.size[1]
        self._sy.draw(
            700,
            height - 84,
            25,
            "「谱面推荐不使用任何算法，仅供参考」",
            self._default_text_color,
            "mm",
        )
        self._sy.draw(
            700,
            height - 36,
            18,
            self._design_text,
            self._default_text_color,
            "mm",
            2,
            (255, 255, 255, 255),
        )
        return image_to_base64(self._im.crop((200, 0, 1200, total_height)))

    def draw_plan(
        self,
        level: str,
        completed: list[PlayedResult],
        completed_y: int,
        unfinished: list[PlayedResult],
        unfinished_y: int,
        notstarted: list[NotPlayedResult],
        plan: str,
        completed_len: int,
    ) -> str:
        """
        绘制进度表

        Params:
            `completed`: `已完成谱面`
            `completed_y`: `已完成谱面高度`
            `unfinished`: `未完成谱面`
            `unfinished_y`: `未完成谱面高度`
            `notstarted`: `未游玩谱面`
            `plan`: `目标`
            `completed_len`: `已完成谱面数量`
        Returns:
            `base64 str`
        """
        max = len(completed + unfinished + notstarted)

        self._im.alpha_composite(self._title_lengthen_bg, (475, 30))
        self._im.alpha_composite(self._title_lengthen_bg, (475, 30 + completed_y))
        self._im.alpha_composite(
            self._title_lengthen_bg, (475, 30 + completed_y + unfinished_y)
        )

        self._sy.draw(
            700,
            77,
            25,
            f"已完成谱面「{len(completed)}」个",
            self._default_text_color,
            "mm",
        )
        self._sy.draw(
            1300,
            77,
            20,
            f"可使用「{level}{plan.upper()}已完成进度」\n指令查询详细列表",
            self._default_text_color,
            "rm",
            2,
            (255, 255, 255, 255),
            True,
        )
        self._sy.draw(
            700,
            77 + completed_y,
            25,
            f"未完成谱面「{len(unfinished)}」个",
            self._default_text_color,
            "mm",
        )
        self._sy.draw(
            1300,
            77 + completed_y,
            20,
            f"可使用「{level}{plan.upper()}未完成进度」\n指令查询详细列表",
            self._default_text_color,
            "rm",
            2,
            (255, 255, 255, 255),
            True,
        )
        self._sy.draw(
            700,
            77 + completed_y + unfinished_y,
            25,
            f"未游玩谱面「{len(notstarted)}」个",
            self._default_text_color,
            "mm",
        )

        self.whiledraw(completed[:completed_len], False, 140)
        self.whiledraw(unfinished[:30], False, 140 + completed_y)
        self._while_pic(notstarted[:100], 140 + completed_y + unfinished_y)

        self._im.alpha_composite(self._design_bg, (200, self._im.size[1] - 133))
        pagemsg = (
            f"「{level}」共计「{max}」个谱面，剩余「{len(unfinished + notstarted)}」"
            f"个谱面未完成「{plan.upper()}」"
        )
        self._sy.draw(
            700, self._im.size[1] - 90, 22, pagemsg, self._default_text_color, "mm"
        )
        self._sy.draw(
            700,
            self._im.size[1] - 30,
            25,
            self._design_text,
            self._default_text_color,
            "mm",
            2,
            (255, 255, 255, 255),
        )
        return image_to_base64(self._im)

    def draw_category(
        self,
        category: Category,
        data: list[PlayedResult] | list[NotPlayedResult],
        page: int = 1,
        end_page: int = 1,
    ) -> str:
        """
        绘制指定进度表

        Params:
            `category`: `类别`
            `data`: `数据`
            `page`: `页数`
            `end_page`: `总页数`
        Returns:
            `base64 str`
        """
        lendata = len(data)
        newdata = data[(page - 1) * 80 : page * 80]
        self._im.alpha_composite(self._title_lengthen_bg, (475, 30))
        if category in [Category.COMPLETED, Category.UNFINISHED]:
            txt = "已完成" if category == Category.COMPLETED else "未完成"
            self._sy.draw(700, 77, 28, f"{txt}谱面", self._default_text_color, "mm")
            self.whiledraw(newdata, False, 140)
            self._im.alpha_composite(self._design_bg, (200, self._im.size[1] - 133))

            pagemsg = (
                f"{txt}谱面共计「{lendata}」个，"
                f"当前第「{(page - 1) * 80 + 1}-{80 * (page - 1) + len(newdata)}」个，"
                f"第「{page} / {end_page}」页"
            )
            self._sy.draw(
                700, self._im.size[1] - 90, 25, pagemsg, self._default_text_color, "mm"
            )
            self._sy.draw(
                700,
                self._im.size[1] - 30,
                25,
                self._design_text,
                self._default_text_color,
                "mm",
                2,
                (255, 255, 255, 255),
            )
        else:
            self._sy.draw(700, 77, 28, "未游玩谱面", self._default_text_color, "mm")
            self._while_pic(data)
            self._im.alpha_composite(self._design_bg, (200, self._im.size[1] - 113))
            self._sy.draw(
                700,
                self._im.size[1] - 70,
                25,
                f"未游玩谱面共计「{len(data)}」个",
                self._default_text_color,
                "mm",
            )
        return image_to_base64(self._im)

    def draw_score_list(
        self,
        rating: str | float,
        play_result: list[PlayedResult],
        page: int,
        end_page: int,
    ) -> str:
        """
        绘制分数列表

        Params:
            `rating`: `定数`
            `play_result`: `游玩成绩`
            `page`: `页数`
            `end_page`: `总页数`
        Returns:
            `base64 str`
        """
        start_offset = (page - 1) * 80
        current_page_result = play_result[start_offset : page * 80]

        height = 140 + (4 * 114)

        for num in range(0, len(current_page_result), 20):
            idx = num // 20
            result = current_page_result[num : num + 20]

            base_y = idx * height
            self._im.alpha_composite(self._title_lengthen_bg, (475, base_y + 20))

            no_start = start_offset + num + 1
            no_end = start_offset + num + len(result)
            self._fot.draw(
                700,
                base_y + 67,
                28,
                f"No.{no_start}- No.{no_end}",
                self._default_text_color,
                "mm",
            )
            self.whiledraw(result, False, base_y + 140)

        canvas_h = self._im.size[1]
        self._im.alpha_composite(self._design_bg, (200, canvas_h - 153))

        footer_text = (
            f"「{rating}」共计「{len(play_result)}」个成绩，"
            f"当前第「{start_offset + 1}-{start_offset + len(current_page_result)}」个，"
            f"第「{page} / {end_page}」页"
        )
        self._sy.draw(
            700, canvas_h - 110, 25, footer_text, self._default_text_color, "mm"
        )
        self._sy.draw(
            700,
            self._im.size[1] - 35,
            25,
            self._design_text,
            self._default_text_color,
            "mm",
            2,
            (255, 255, 255, 255),
        )
        return image_to_base64(self._im)
