from PIL import Image, ImageDraw

from ...config import maiconfig
from ...resources import FOTNEWRODIN, SIYUAN, pic_dir
from ..merge.models import Song, Theme
from .assets import AssetsImage
from .base import change_column_width, coloum_width
from .tools import (
    DrawText,
    generate_frosted_card,
    image_to_base64,
    song_chart,
    tricolor_gradient_prism_plus,
)

PAGE_SIZE = 14


def song_list(songs: list[Song], page: int) -> str:
    """
    绘制曲目列表

    Params:
        `songs`: 曲目列表
        `page`: 页数
    Returns:
        `base64 str`
    """
    assets = AssetsImage()
    total_page = max(1, (len(songs) + PAGE_SIZE - 1) // PAGE_SIZE)
    page = max(1, min(page, total_page))

    start = (page - 1) * PAGE_SIZE
    end = start + PAGE_SIZE
    songs = songs[start:end]

    lines = sum(divmod(len(songs), 2))
    height = 200 + lines * 145 + 200

    _im = tricolor_gradient_prism_plus(1000, height)
    _im.alpha_composite(assets._aurora_bg.resize((1000, 174)))
    _im.alpha_composite(assets._shines_bg.resize((1000, 442)))
    pattern = assets._pattern_bg.resize((1000, 256))
    for h in range((height // 256) + 1):
        _im.alpha_composite(pattern, (0, (256 + 6) * h))
    _im.alpha_composite(assets._rainbow_bg.resize((550, 288)), (225, height - 435))
    _im.alpha_composite(
        assets._rainbow_bottom_bg.resize((786, 164)),
        (107, height - 260),
    )

    im = generate_frosted_card(_im, (50, 150, 950, 150 + lines * 145 + 100), alpha=0.2)
    dr = ImageDraw.Draw(im)
    sy = DrawText(dr, SIYUAN)
    fot = DrawText(dr, FOTNEWRODIN)

    chara = (
        Image.open(pic_dir / Theme.PRISM_PLUS.value / "chara_left.png")
        .convert("RGBA")
        .resize((156, 187))
    )
    im.alpha_composite(chara, (800, 0))
    im.alpha_composite(assets._moon_bg.resize((120, 120)), (60, 20))
    im.alpha_composite(
        Image.open(pic_dir / "maimai でらっくす PRiSM PLUS.png").resize((210, 101)),
        (15, 20),
    )

    x_gap = 450
    y_gap = 145
    start_x = 70
    start_y = 200
    text_color = (124, 129, 255, 255)
    for num, song in enumerate(songs):
        row, col = divmod(num, 2)
        x = start_x + col * x_gap
        y = start_y + row * y_gap

        im.alpha_composite(assets._card_bg, (x, y))
        cover = Image.open(song_chart(song.song_id)).resize((80, 80))
        version = Image.open(pic_dir / f"{song.version_str}.png").resize((104, 50))
        type_ = Image.open(pic_dir / f"{song.type.upper()}.png").resize((40, 15))

        im.alpha_composite(cover, (x + 10, y + 10))
        im.alpha_composite(version, (x + 315, y - 30))
        im.alpha_composite(
            assets._sl_diff_utg if song.song_id > 100000 else assets._sl_diff_bg,
            (x + 100, y + 95),
        )
        im.alpha_composite(type_, (x + 50, y + 75))

        fot.draw(x + 50, y + 105, 15, song.song_id, text_color, "mm")
        title = song.song_name
        if coloum_width(title) > 20:
            title = change_column_width(title, 19) + "..."
        fot.draw(x + 100, y + 25, 20, title, text_color, "lm")
        artist = song.artist
        if coloum_width(artist) > 26:
            artist = change_column_width(artist, 25) + "..."
        fot.draw(x + 100, y + 50, 12, artist, text_color, "lm")
        fot.draw(x + 100, y + 80, 15, f"BPM: {song.bpm}", text_color, "lm")
        sy.draw(x + 230, y + 80, 12, song.genre, text_color, "lm")
        if song.song_id > 100000:
            diff = song.difficulties[0]
            fot.draw(
                x + 125 + 50 * diff.level_index,
                y + 105,
                15,
                diff.level_value,
                (255, 255, 255, 255),
                "mm",
            )
        else:
            for diff in song.difficulties:
                if diff.level_index != 4:
                    color = (255, 255, 255, 255)
                else:
                    color = (138, 0, 226, 255)
                fot.draw(
                    x + 125 + 50 * diff.level_index,
                    y + 105,
                    15,
                    diff.level_value,
                    color,
                    "mm",
                )

    fot.draw(
        500,
        70,
        55,
        "曲目列表",
        AssetsImage._default_text_color,
        "mm",
        3,
        (255, 255, 255, 255),
    )
    fot.draw(
        500,
        height - 100,
        35,
        f"Page {page}/{total_page}",
        AssetsImage._default_text_color,
        "mm",
        3,
        (255, 255, 255, 255),
    )
    fot.draw(
        500,
        height - 30,
        18,
        f"Designed by Yuri-YuzuChaN & BlueDeer233. Generated by {maiconfig.bot_name} BOT",
        AssetsImage._default_text_color,
        "mm",
        3,
        (255, 255, 255, 255),
    )
    return image_to_base64(im)
