import time
from io import BytesIO
from pathlib import Path

import aiofiles
from PIL import Image, ImageDraw

from ...config import log, maiconfig
from ...constants import DX_VERSION, LEVEL_LIST, PLATE_CN, VERSION_MAP
from ...resources import FOTNEWRODIN, TBFONT, pic_dir, plate_table_dir, rating_table_dir
from ..merge.models import Song
from ..service import mai
from .assets import AssetsImage
from .tools import (
    DrawText,
    generate_frosted_card,
    song_chart,
    tricolor_gradient_prism_plus,
)


class UpdateTable(AssetsImage):
    _font_color = (114, 188, 254, 255)

    def __init__(self):
        super().__init__()
        self.level_list = LEVEL_LIST[6:]
        self.version_list = list(_ for _ in DX_VERSION.keys())[1:]

    def _generate_bg(self, height: int, separator_height: int) -> Image.Image:
        """
        生成定数表背景

        Params:
            `height`: 背景高度
            `separator_height`: 分割线高度
        Returns:
            `Image.Image`
        """
        im = tricolor_gradient_prism_plus(1400, height)
        im.alpha_composite(self._aurora_bg)
        im.alpha_composite(self._shines_bg, (11, 6))
        im.alpha_composite(self._rainbow_bg, (318, height - 545))
        im.alpha_composite(self._rainbow_bottom_bg, (122, height - 305))
        for h in range((height // 358) + 1):
            im.alpha_composite(self._pattern_bg, (0, (358 + 7) * h))
        im.alpha_composite(self._separator_bg, (100, separator_height))
        return im

    async def _save_image(self, im: Image.Image, path: Path) -> None:
        """
        保存图片到本地

        Params:
            `im`: PIL图像
            `path`: 路径
        """
        by = BytesIO()
        im.save(by, "PNG")
        async with aiofiles.open(path, "wb") as f:
            await f.write(by.getbuffer())

    async def update_level_15_rating_table(self):
        """单独绘制等级 15的定数表"""
        draw_time = time.time()
        lv15 = mai.total_level_data["15"]["15.0"]
        count = len(lv15)
        lines = (count // 3) + (1 if count % 3 else 0)
        height = 650 + lines * 450

        im = self._generate_bg(height, 360)

        dr = ImageDraw.Draw(im)
        fot = DrawText(dr, FOTNEWRODIN)

        fot.draw(
            700,
            height - 75,
            30,
            f"Designed by Yuri-YuzuChaN & BlueDeer233. Generated by {maiconfig.bot_name} BOT",
            self._font_color,
            "mm",
        )

        unknown_chart = Image.open(song_chart(0)).convert("RGBA").resize((330, 330))
        for i in range(lines * 3):
            row, col = divmod(i, 3)

            x = 100 + col * 425
            y = 500 + row * 450

            im.alpha_composite(self._chart_white_bg, (x, y))
            if i < count:
                song = lv15[i]
                chart = Image.open(song_chart(song.song_id)).convert("RGBA")
                im.alpha_composite(chart.resize((330, 330)), (x + 10, y + 10))
                im.alpha_composite(self._table_type_bg[song.type], (x + 200, y + 345))
                im.alpha_composite(
                    Image.open(pic_dir / f"{song.version_str}.png").resize((332, 160)),
                    (x + 9, y - 80),
                )
                fot.draw(x + 100, y + 370, 35, song.song_id, self._font_color, "mm")
            else:
                im.alpha_composite(unknown_chart, (x + 10, y + 10))
                im.alpha_composite(self._table_type_bg["DX"], (x + 200, y + 345))
                fot.draw(x + 100, y + 370, 35, "????", self._font_color, "mm")
                fot.draw(
                    x + 175,
                    y + 280,
                    30,
                    "UNKNOWN",
                    self._font_color,
                    "mm",
                    8,
                    (255, 255, 255, 255),
                )

        await self._save_image(im, rating_table_dir / "15.png")
        log.info(f"lv.15 定数表更新完成，耗时：{time.time() - draw_time:.3f}s")

    async def update_rating_table(self):
        """绘制定数表"""
        for lv in self.level_list[:-1]:
            single_time = time.time()
            lvlist = mai.total_level_data[lv]

            GRID_STEP = 85  # 每个曲绘的间距 (75曲绘 + 10间距)
            START_X = 140  # 曲绘起始x轴坐标

            current_y = 450  # 曲绘起始y轴坐标
            for songs in lvlist.values():
                if not songs:
                    continue
                rows = (len(songs) - 1) // 14 + 1
                current_y += rows * GRID_STEP + 30

            height = current_y + 230

            _im = self._generate_bg(height, 360)
            im = generate_frosted_card(_im, (50, 404, 1350, current_y))

            dr = ImageDraw.Draw(im)
            tb = DrawText(dr, TBFONT)
            fot = DrawText(dr, FOTNEWRODIN)

            fot.draw(
                700,
                height - 75,
                30,
                f"Designed by Yuri-YuzuChaN & BlueDeer233. Generated by {maiconfig.bot_name} BOT",
                self._font_color,
                "mm",
            )

            START_Y = 450  # 曲绘起始y轴坐标
            for ds, songs in lvlist.items():
                if not songs:
                    continue

                _ds = ds.split(".")[-1]
                fot.draw(
                    70,
                    START_Y + 35,
                    40,
                    f".{_ds}",
                    self._font_color,
                    "lm",
                    4,
                    (255, 255, 255, 255),
                )

                max_row = 0
                for num, song in enumerate(songs):
                    row, col = divmod(num, 14)
                    max_row = max(max_row, row)

                    x = START_X + col * GRID_STEP
                    y = START_Y + row * GRID_STEP

                    cover = Image.open(song_chart(song.song_id)).resize((75, 75))
                    im.alpha_composite(cover, (x, y))
                    im.alpha_composite(
                        self._table_diff_bg[song.difficulties.level_index],
                        (x - 5, y - 5),
                    )
                    tb.draw(
                        x + 56,
                        y + 4,
                        13,
                        song.song_id,
                        self._diff_text_color[song.difficulties.level_index],
                        "mm",
                    )
                START_Y += (max_row + 1) * GRID_STEP + 30

            await self._save_image(im, rating_table_dir / f"{lv}.png")
            log.info(f"lv.{lv} 定数表更新完成，耗时：{time.time() - single_time:.3f}s")

    def _get_level_dict(self) -> dict[str, list[Song]]:
        return {lv: [] for lv in reversed(LEVEL_LIST)}

    def _get_song_list(self, version_name: str) -> list[Song]:
        """
        获取指定版本曲目列表

        Params:
            `version_name`: 版本名字
        Ruturns:
            `list[Song]`
        """
        song_id_list = mai.total_plate_id_list[version_name]
        song_list = mai.total_list.by_id_list(song_id_list)
        return song_list

    def _draw_plate(
        self,
        level_dict: dict[str, list[Song]],
        song_id_list: list[int] | None = None,
        remaster_song_list: list[Song] | None = None,
        pages: int | None = None,
    ) -> Image.Image:
        """
        绘制所有曲绘

        Params:
            `level_dict`: 曲目数据字典
            `remaster_song_list`: 白谱曲目数据列表
            `pages`: 舞/霸者 牌子页数
        Returns:
            `Image.Image`
        """
        GRID_STEP = 96  # 每个曲绘的间距 (80曲绘 + 16间距)
        START_X = 180  # 曲绘起始x轴坐标

        current_y = 490  # 曲绘起始y轴坐标
        for songs in level_dict.values():
            if not songs:
                continue
            rows = (len(songs) - 1) // 12 + 1
            current_y += rows * GRID_STEP + 30

        height = current_y + 180

        _im = self._generate_bg(height, 400)
        im = generate_frosted_card(_im, (50, 444, 1350, current_y))

        dr = ImageDraw.Draw(im)
        tb = DrawText(dr, TBFONT)
        fot = DrawText(dr, FOTNEWRODIN)

        if pages is not None:
            fot.draw(
                700, height - 140, 40, f"Pages {pages + 1}/2", self._font_color, "mm"
            )
        fot.draw(
            700,
            height - 75,
            30,
            f"Designed by Yuri-YuzuChaN & BlueDeer233. Generated by {maiconfig.bot_name} BOT",
            self._font_color,
            "mm",
        )

        START_Y = 490  # 曲绘起始y轴坐标
        for ds, songs in level_dict.items():
            if not songs:
                continue

            def get_ds_sort_key(song: Song):
                if song_id_list is not None and remaster_song_list is not None:
                    if song.song_id in song_id_list and song in remaster_song_list:
                        return song.difficulties[4].level_value
                return song.difficulties[3].level_value

            songs.sort(key=get_ds_sort_key, reverse=True)
            fot.draw(
                72,
                START_Y + 40,
                40,
                ds,
                self._font_color,
                "lm",
                4,
                (255, 255, 255, 255),
            )

            max_row = 0
            for num, song in enumerate(songs):
                row, col = divmod(num, 12)
                max_row = max(max_row, row)

                x = START_X + col * GRID_STEP
                y = START_Y + row * GRID_STEP

                cover = song_chart(song.song_id)
                im.alpha_composite(Image.open(cover).resize((80, 80)), (x, y))
                if remaster_song_list is not None and song in remaster_song_list:
                    _id_bg = self._table_wu_rms_id_bg
                else:
                    _id_bg = self._table_id_bg
                im.alpha_composite(_id_bg, (x - 5, y - 5))
                id_color = (255, 255, 255, 255)
                if remaster_song_list is not None and song in remaster_song_list:
                    id_color = (138, 0, 226, 255)
                tb.draw(x + 56, y + 4, 16, song.song_id, id_color, "mm")
            START_Y += (max_row + 1) * GRID_STEP + 30
        return im

    async def update_wu_plate_table(self):
        """
        更新「霸者」/「舞」牌
        """
        single_time = time.time()
        song_list = self._get_song_list("舞")
        song_id_list = mai.total_plate_id_list["舞ReMASTER"]
        remaster_song_list = self._get_song_list("舞ReMASTER")

        all_level_dict = self._get_level_dict()

        for s in song_list:
            if s.song_id in song_id_list:
                all_level_dict[s.difficulties[4].level].append(s)
            else:
                all_level_dict[s.difficulties[3].level].append(s)

        keys = list(all_level_dict.keys())

        idx = keys.index("13")

        lv_13_plus = {k: all_level_dict[k] for k in keys[:idx]}
        lv_13_low = {k: all_level_dict[k] for k in keys[idx:]}

        for pages, level_dict in enumerate([lv_13_plus, lv_13_low]):
            im = self._draw_plate(level_dict, song_id_list, remaster_song_list, pages)
            await self._save_image(im, plate_table_dir / f"舞-{pages + 1}.png")

        log.info(f"舞/霸者完成表更新完成，耗时：{time.time() - single_time:.3f}s")

    async def update_plate_table(self) -> str:
        """
        更新版本牌子

        Returns:
            `str`
        """
        all_time = 0
        for name in self.version_list:
            single_time = time.time()
            if name in PLATE_CN:
                name = PLATE_CN[name]
            ver, version_name = VERSION_MAP.get(name, ([DX_VERSION.get(name)], name))

            song_list = self._get_song_list(version_name)
            level_dict = self._get_level_dict()

            for s in song_list:
                level_dict[s.difficulties[3].level].append(s)

            im = self._draw_plate(level_dict)
            await self._save_image(im, plate_table_dir / f"{name}.png")

            s_time = round(time.time() - single_time, 3)
            all_time += s_time
            log.info(f"{name}代牌子更新完成，耗时：{s_time}s")
        result = f"完成表更新完成，耗时：{all_time}s"
        log.info(result)
        return result
